name: Check for version increments and apply them if necessary 

on:
  workflow_call:
    inputs:
      botName:
        description: The name of the bot that adds the necessary version increment changes
        type: string
        required: true
      botMail:
        description: The name of the bot that adds the necessary version increment changes
        type: string
        required: true
      excludedProjects:
        description: The comma-separated list of projects that should not be skipped (e.g. products or repositories). Can speed-up the check
        type: string
        required: false
        default: ''
    secrets:
      githubBotPAT:
        description: The personal access token (with scope 'public_repo') of the bot to push a required change to a PR branch in a fork.
        required: false

permissions:
  contents: read
  issues: write

jobs:
  versions-check-and-increment:
    name: Check and increment service versions
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: '${{ github.event.pull_request.head.sha }}'
        persist-credentials: false #Opt out from persisting the default Github-token authentication in order to enable use of the bot's PAT when pushing below
#        token: ${{ secrets.githubBotPAT }} TODO: alternativly use this and and just add the fork without basic auth below.
    - name: Check and increment versions
      uses: Wandalen/wretry.action@6feedb7dedadeb826de0f45ff482b53b379a7844 # master
      with:
        attempt_delay: 200
        attempt_limit: 10
        command: |
             echo 'Hello World'>someFile.txt
             echo 'Hello World 2'>someFile2.txt
             ls
#            mvn clean verify -B -fae -T 1C
#            org.eclipse.tycho:tycho-versions-plugin:bump-versions
#            -DskipTests
#            -Dcompare-version-with-baselines.skip=false
#TODO: exclude products, p2-repos etc:
# https://stackoverflow.com/questions/13266470/how-do-i-exclude-certain-modules-from-a-maven-build-using-the-commandline
# Do something like -pl '!excludedProjects.replace(',','!,')'
# Or create a list of all eclipse-plugin and eclipse-feature projects and use it here as input for PL?! Could be done with java-script?!
# Or check if one can just compute the build-qualifier and then run the baseline plugin?!

    - id: git-commit
      name: Commit and push version increments, if any
      run: |
        if [[ $(git status --ignore-submodules --porcelain) != '' ]]; then
          # Workspace is not clean, i.e. some version were changed
          
          # Read pom project parent version or project version as development stream version
          sudo apt-get install -qq -y libxml2-utils
          pomVersion=$(xmllint --xpath "(/*[local-name()='project']/*[local-name()='parent'] | /*[local-name()='project'])/*[local-name()='version']/text()" pom.xml)
          streamVersion=$(echo "${pomVersion}" | cut -d '.' -f1-2)
          
          git config --global user.email '${{ inputs.botMail }}'
          git config --global user.name '${{ inputs.botName }}'
          git add --all
          git status
          git commit -m "Bump version(s) for ${streamVersion} stream"
          
          fileList=$(git diff-tree --no-commit-id --name-only HEAD -r)
          echo "file-list<<EOF" >> $GITHUB_OUTPUT
          echo "$fileList" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          git format-patch -1 HEAD --no-prefix --no-stat --output 'version_increments.patch'
          
          #git remote add 'fork' https://github.com/${{ github.event.pull_request.head.repo.full_name }}.git
          #git remote -v
          #git push 'fork' 'HEAD:refs/heads/${{ github.event.pull_request.head.ref }}'
          git push \
            "https://oauth2:${BOT_TOKEN}@github.com/${{ github.event.pull_request.head.repo.full_name }}.git" \
            'HEAD:refs/heads/${{ github.event.pull_request.head.ref }}'
          
        else
          echo 'No versions have to be incremented'
        fi
      env:
        BOT_TOKEN: ${{ secrets.githubBotPAT || secrets.GITHUB_TOKEN }}

    - name: Add information comment
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      if: ${{ always() }} 
      with:
        github-token: ${{ secrets.githubBotPAT || secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs')
          const fileList = `${{ steps.git-commit.outputs.file-list }}`
          if (fileList) { // if list is empty, no versions were changed
            let commentBody = 
            github.rest.issues.createComment({
              issue_number: context.issue.number, ...context.repo, body: `
          This pull request changes some projects for the first time in this development.
          Therefore the following files need a version increment:
          \`\`\`
          ${fileList}
          \`\`\`
          An additional commit containing all the necessary changes was pushed to the top of this PR's branch. To obtain these changes (for example if you want to push more changes) either fetch from your fork or apply the _git patch_.
          <details>
          <summary>Git patch</summary>
          
          \`\`\`
          ${ fs.readFileSync( process.env.GITHUB_WORKSPACE + '/version_increments.patch', {encoding: 'utf8'}).trim() }
          \`\`\`
          </details>
          `.trim()
            })
          }

# TODO: Add an FAQ about version bumps?
# TODO: make comment updatable