# Fast running checks for pull-requests

name: Pull-Request Checks
concurrency: 
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

on:
  pull_request:
    branches: [ master ]

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
  check-freeze-period:
    uses: ./.github/workflows/verifyFreezePeriod.yml
  check-merge-commits:
    uses: ./.github/workflows/checkMergeCommits.yml
  check-versions:
    # Run this check only for PRs from forks and not for changes from bots created on branches in this repository
    if: github.event.pull_request.head.repo.full_name != 'eclipse.platform/eclipse.platform.releng.aggregator'
    uses: ./.github/workflows/checkVersions.yml
    with:
      botName: Eclipse Platform Bot
      botMail: platform-bot@eclipse.org
      # Only check 'eclipse.platform.releng' projects
      working-directory: 'eclipse.platform.releng'
      extra-maven-args: '-Pbuild-individual-bundles'
