# Fast running checks for pull-requests

name: Pull-Request Checks
concurrency: 
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

on:
  push:

jobs:
  check-freeze-period:
    uses: ./.github/workflows/verifyFreezePeriod.yml
