name: Publish Unit Test Results

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

jobs:
    check:
       uses: HannesWell/eclipse.platform.releng.aggregator/.github/workflows/publishVersionCheckResults.yml@master
